### ISSUE TITLE
Using lerobot/svla_so100_stacking throws pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>'

### ISSUE THREAD

**Issue by nijkah** [huggingface/lerobot#2268]
### System Info

```Shell
lerobot: main branch: b954337ac7c8db5ea592c0d59dfb435845d9d380
OS: Ubuntu 22.04
Python 3.11.13
Torch version: 2.7.1+cu118
```

### Information

- [x] One of the scripts in the examples/ folder of LeRobot
- [ ] My own task or dataset (give details below)

## Error Message
```
  File "/workspace/new/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 102, in __init__
    self.load_metadata()
  File "/workspace/new/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 162, in load_metadata
    self.tasks = load_tasks(self.root)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/new/lerobot/src/lerobot/datasets/utils.py", line 338, in load_tasks
    tasks = pd.read_parquet(local_dir / DEFAULT_TASKS_PATH)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parquet.py", line 669, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parquet.py", line 265, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 1843, in read_table
    dataset = ParquetDataset(
              ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 1413, in __init__
    [fragment], schema=schema or fragment.physical_schema,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 1473, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

## Note
There is a error message in https://huggingface.co/datasets/lerobot/svla_so100_stacking/blob/main/meta/tasks.parquet

## Test Script
```
lerobot-train \
  --policy.path=lerobot/smolvla_base \
  --dataset.repo_id=lerobot/svla_so100_stacking \
  --batch_size=64 \
  --steps=20000 \
  --output_dir=outputs/train/my_smolvla \
  --job_name=my_smolvla_training \
  --policy.device=cuda \
  --policy.push_to_hub=false \
  --wandb.enable=false
```

### Expected behavior

https://huggingface.co/docs/lerobot/en/smolvla#finetune-smolvla-on-your-data

## Previous related comments
- https://github.com/huggingface/lerobot/issues/2035#issuecomment-3393035394

**Comment by michel-aractingi** [comment]
Hello can you remove this dataset from your cache and try again? The dataset was corrupt. We pushed a fix so it should work now. 

Your cache is typically in `~/.cache/huggingface/lerobot`

**Comment by nijkah** [comment]
@michel-aractingi Hello, I deleted the dataset in the cache path (~/.cache/huggingface/lerobot/lerobot/svla_so100_stacking) and retried it.
I think there is still an issue. May I ask you to check it agian?

```
...

INFO 2025-10-21 23:06:21 ot_train.py:225 Logs will be saved locally.
INFO 2025-10-21 23:06:21 ot_train.py:237 Creating dataset
stats.json: 5.81kB [00:00, 15.9MB/s]                                                                                                                                                  | 0/4 [00:00<?, ?it/s]
info.json: 2.62kB [00:00, 11.9MB/s]rquet:   0%|                                                                                                                                   | 0.00/130 [00:00<?, ?B/s]
meta/tasks.parquet: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 129/129 [00:01<00:00, 127B/s]
meta/episodes/chunk-000/file-000.parquet: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 130/130 [00:01<00:00, 119B/s]
Fetching 4 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.54it/s]
Traceback (most recent call last):
  File "/workspace/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 102, in __init__
    self.load_metadata()
  File "/workspace/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 160, in load_metadata
    self.info = load_info(self.root)
                ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lerobot/src/lerobot/datasets/utils.py", line 284, in load_info
    info = load_json(local_dir / INFO_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lerobot/src/lerobot/datasets/utils.py", line 251, in load_json
    with open(fpath) as f:
         ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/lerobot/lerobot/svla_so100_stacking/meta/info.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/lerobot-train", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspace/lerobot/src/lerobot/scripts/lerobot_train.py", line 494, in main
    train()
  File "/workspace/lerobot/src/lerobot/configs/parser.py", line 233, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lerobot/src/lerobot/scripts/lerobot_train.py", line 238, in train
    dataset = make_dataset(cfg)
              ^^^^^^^^^^^^^^^^^
  File "/workspace/lerobot/src/lerobot/datasets/factory.py", line 88, in make_dataset
    ds_meta = LeRobotDatasetMetadata(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 109, in __init__
    self.load_metadata()
  File "/workspace/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 162, in load_metadata
    self.tasks = load_tasks(self.root)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lerobot/src/lerobot/datasets/utils.py", line 338, in load_tasks
    tasks = pd.read_parquet(local_dir / DEFAULT_TASKS_PATH)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parquet.py", line 669, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parquet.py", line 265, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 1843, in read_table
    dataset = ParquetDataset(
              ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 1413, in __init__
    [fragment], schema=schema or fragment.physical_schema,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 1473, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

FileNotFoundError is not shown when I retried the script, but the pyrarrow error still exists.
(installed pyarrow version: 21.0.0 as in requirements-ubuntu.txt)

**Comment by nijkah** [comment]
When I checked the current meta/tasks.parquet (https://huggingface.co/datasets/lerobot/svla_so100_stacking/blob/main/meta/tasks.parquet) and the previous one (https://huggingface.co/datasets/lerobot/svla_so100_stacking/commit/2bceb40b2558544726a45626a2b225bf7233e161#d2h-431370), it seems to be the same file.

**Comment by michel-aractingi** [comment]
sorry @nijkah could you try again, I reconverted the dataset to V3.0

you need to removed the dataset from your cache to download the fixed ones

now the tasks has been updated

**Comment by nijkah** [comment]
@michel-aractingi Thanks! I checked that it works. And related datasets (lerobot/svla_so100_pickplace, lerobot/svla_so100_sorting) also work.
