### ISSUE TITLE
Question about so100_to_so100_EE: should I re-calibrate to let my real robot looks same to so101.urdf?

### ISSUE THREAD

**Issue by milong26** [huggingface/lerobot#2413]
Hi thanks for great work to so100_to_so100_EE.
I tried record.py and found some bad  teleoperate actions such as leader turning around slowly but follower must turn around very fast.

I also tried to use collect(lerobot's default joint-space action) first and transfer joint data to ee data and use ik on ee data. It shows some little variance between real joint action and resulted joint action from ee, which causes the robot cannot do complex jobs.

I know ik may cause some problem but I want to make the influence smaller. Should I re-calibrate again? to fit into urd file and IS my so100 robot is out-of-date?

Thanks!!

**Comment by boyangshen** [comment]
Hi, I think I met the similar problem. But I didn't try transferring joint data to ee data. Could you show your code about IK and if you used the newest urdf ?

**Comment by milong26** [comment]
@boyangshen hi! I choosed to collect data with ik at first instead of collecting joint data and transfer. It works better in inference.
What kinds of code you want to see? I have finished async inference on ee (xD copy async_client) But saving episode is hard to me :P
I was thinking of collect joint and ee data and named them as "action.joint.shoulder_pos/gripper_pos/..." and "action.ee.x/y/z..." but it needs more understanding on LerobotDataset

**Comment by boyangshen** [comment]
> Hi thanks for great work to so100_to_so100_EE. I tried record.py and found some bad teleoperate actions such as leader turning around slowly but follower must turn around very fast.
> 
> I also tried to use collect(lerobot's default joint-space action) first and transfer joint data to ee data and use ik on ee data. It shows some little variance between real joint action and resulted joint action from ee, which causes the robot cannot do complex jobs.
> 
> I know ik may cause some problem but I want to make the influence smaller. Should I re-calibrate again? to fit into urd file and IS my so100 robot is out-of-date?
> 
> Thanks!!

So the questions  `re-calibrate` and `fit into urdf file` are resolved ? I mean which way do you finish inference with ee pose?
As for `saving episode`, maybe you can implement  a custom LerobotDataset recording using `add_frame()` api.

**Comment by milong26** [comment]
@boyangshen No, I didn’t solve it. It’s really hard to recalibrate accurately because the calibration is done by human hands and eye alignment, and that method can’t be very precise. So instead, I collect data by teleoperating in end-effector space. This way, I can get good action data that can reliably make the follower perform exactly the actions I want.
Thanks! I did use `add_frame` to colelct new type data.

**Comment by boyangshen** [comment]
I do not understand teleoperating in end-effector space cause I just recorded data with leader arm and got joint position. Mabe I will try it later.

**Comment by milong26** [comment]
@boyangshen Only recording joint-position and fk to get ee works well, but ik from the ee may got different results which leads robot move different.
You can try to calibrate to an exact position, but it's hard

**Comment by boyangshen** [comment]
Thanks for your explaination! The IK results are different from those original joint position according to the multiple solutions ？ The ee pose is also different ？

**Comment by milong26** [comment]
@boyangshen Yes I think, since in placo its initial position is different from in reality since our hand is not very exact

**Comment by boyangshen** [comment]
Pardon. My meaning is that the reason of differences is  the multiple solutions or other error. Former is normal  according to mathematical principles but latter is unnormal. And former the ee pose keep same with initial position but latter is not. So what is the performance ?

**Comment by milong26** [comment]
@boyangshen I don't know, you can devote into it. My meaning is that latter is mostly caused by the basic model used by Placo for kinematics and the errors caused by calibration in a real robot

**Comment by boyangshen** [comment]
Fine. Thanks to your feedback! @milong26

**Comment by ZhenghaoFei** [comment]
> [@boyangshen](https://github.com/boyangshen) hi! I choosed to collect data with ik at first instead of collecting joint data and transfer. It works better in inference. What kinds of code you want to see? I have finished async inference on ee (xD copy async_client) But saving episode is hard to me :P I was thinking of collect joint and ee data and named them as "action.joint.shoulder_pos/gripper_pos/..." and "action.ee.x/y/z..." but it needs more understanding on LerobotDataset

Hi @milong26 ! Can you explain more about what is " collect data with ik at first "? You said this can lead to better results in inference. Do you mean to teleop using EE control and solve ik in data collection and get joints and save?

**Comment by milong26** [comment]
@ZhenghaoFei yes collect using its record.py instead of lerobot_record.py.

**Comment by paulpacaud** [comment]
@milong26 have you found a way to correct the URDF "zero" joint values with your personal calibration?

The FK uses the URDF joint origins as the reference. Your personal calibration ensures that when your robot is at its physical "middle/zero" position, the motors report values around mid = (range_min + range_max) / 2.                                                                                                                                                                                       
                                                                                                                                                                                                          
BUT: If your physical "middle" position during calibration doesn't exactly match the URDF's expected zero pose, the FK will have an offset.                                                             
                                                                                                                                                                                                          
The so101_new_calib.urdf was designed with joint origins that match a "standard" calibration procedure. If your calibration procedure differed slightly (e.g., robot wasn't perfectly at the expected pose when you pressed "Enter"), there will be discrepancies.

**Comment by milong26** [comment]
@paulpacaud Not yet ;-; The only way I can do is calibrate more accuratly (by my eye)

**Comment by yuzzzdi** [comment]
Is anyone able to find a solution to this issue?

**Comment by milong26** [comment]
> Is anyone able to find a solution to this issue?

i think it's ok to not re-calibrate. Since when u use so100_to_so100_ee, teleoperation will make the robot do actions you want
But there are still some problem in ik

**Comment by yuzzzdi** [comment]
Hi, Even i was trying something similar but ik solutions that are calculated using kinematics.py are really bad, like when i try to replay it.

**Comment by milong26** [comment]
> Hi, Even i was trying something similar but ik solutions that are calculated using kinematics.py are really bad, like when i try to replay it.

@yuzzzdi  Hi, how you record dataset? I did this: recording using ik(get joint from leader,calculate ee,sens ee to follower, calculate follower's joint) and then replay by ee. It should get right joint result.

**Comment by yuzzzdi** [comment]
@milong26. Could this cause any issues during teleoperation? There’s a lot of reading and writing going on, plus the calculations.

When I record, I use the leader's joint angles to figure out the forward kinematics (FK) with the follower's URDF. This saves the end effector positions (ee_x, ee_y, ee_z, etc.) in the dataset. 

During replay, I do inverse kinematics (IK) with the end effector data and write the joint angles for the follower. But the replay isn't good; the follower moves in a really strange way, and the movements don’t match the end effector's position from the recording.


PS: Is it possible to train the model to predict end effector data and would any other changes be needed?

**Comment by milong26** [comment]
@yuzzzdi 
1. It will cause some issue during teleoperation : I saw follower arm turn around quickly because  leader fk -> follower ik extends its range in one direction. The solver will give a new different direction solution which makes robot turn around quickly. So make sure your teleoperation not close to boundary. But luckily when evalutate with policy, it seldom show this, maybe I didn't save such episodes.
2.  Do you use so100_to_so100_ee record and replay code? It shouldwork well if it behaves well when recording.
3. `write the joint angles for the follower` The code works as "controling by ee and writing ee", writing joint angles maybe not correct since there is a latency between `send_action(joint)` and `the robot's joint_action is same as requirement` in both time and exact position especially when use_degrees.
4. Is it possible to train the model to predict end effector data ? ==> yes if you train with ee type action data. (Maybe you can train with collected joint_type data? but idk whether it works well. since there is some error when doing fk and ik.) The best way is collect ee data(here action data can lead follower finish task.) and train (the output action should lead follower to finishi same task too) 

My english is bad so you can feed my answer to AI to understand. =)

**Comment by LaFeuilleMorte** [comment]
Hi，I was recently dealing with EEF pose data collection/convertion/training. I can replay normally with dataset recored from examples/so100_to_so100_EE/record.py，but when I use this dataset to train a model (ACT for example), the inference results become really bad, the arm was doing non-sense movements, far different from the results during replay. I managed to tune th e IK solver. And found that I needed to regularize the IK solver:

```python
def set_energy_reg(kinematics: RobotKinematics, delta_t):

    solver = kinematics.solver

    # 加阻尼
    solver.add_regularization_task(1e-2)
```
The results became much better. But there're still some unreasonable movements. Does anything manager to train a eef model and successfully inference with it?

**Comment by yuzzzdi** [comment]
Thank you, @milong26 . I implemented the method from the examples, and it's working well, except for some recordings that start off poorly. 

In the initial stages of the replay, the follower moves randomly for the first few actions but then corrects itself. Do you have any idea what could be causing this?

**Comment by yuzzzdi** [comment]
@milong26  WARNING: root: The record loop is running slower at 15.5 Hz compared to the target FPS of 30 Hz. This may result in dropped dataset frames and unstable robot control. Common causes for this issue include: 1) The camera's FPS is not keeping up, 2) Policy inference is taking too long, or 3) CPU starvation. 

Have you encountered a similar problem?

**Comment by milong26** [comment]
@yuzzzdi 
> In the initial stages of the replay, the follower moves randomly for the first few actions but then corrects itself. Do you have any idea what could be causing this?
Yes, I think it is due to 1. ik solver 2. robot so I think it's not easy to fix it 

>  The record loop is running slower at 15.5 Hz
I use policy_server and robot_client inference so I didn't see it 🤔  Maybe it happened but I dismiss
