### ISSUE TITLE
Invalid frame index when training on merged datasets [RuntimeError]

### ISSUE THREAD

**Issue by RiccardoIzzo** [huggingface/lerobot#2680]
### Ticket Type

🐛 Bug Report (Something isn't working)

### Environment & System Info

```Shell
- LeRobot version: 0.4.3
- Platform: Linux-5.4.0-165-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface Hub version: 0.35.3
- Datasets version: 4.1.1
- Numpy version: 2.2.6
- FFmpeg version: 4.4.2-0ubuntu0.22.04.1
- PyTorch version: 2.7.1+cu126
- Is PyTorch built with CUDA support?: True
- Cuda version: 12.6
- GPU model: Quadro RTX 6000
- Using GPU in script?: <fill in>
- lerobot scripts: ['lerobot-calibrate', 'lerobot-dataset-viz', 'lerobot-edit-dataset', 'lerobot-eval', 'lerobot-find-cameras', 'lerobot-find-joint-limits', 'lerobot-find-port', 'lerobot-imgtransform-viz', 'lerobot-info', 'lerobot-record', 'lerobot-replay', 'lerobot-setup-motors', 'lerobot-teleoperate', 'lerobot-train']
```

### Description

I'm having a problem when training a VLA with `lerobot-train` on a merged dataset.
I'm aware of the issue #2627 as well as PR #2550 that is supposed to fix the bug.
However, the problem is still occurring on the latest commit (4a151a9) of lerobot 0.4.3.

The dataset has been merged with the following script:
`lerobot-edit-dataset \
  --repo_id whosricky/so101-megamix-v1 \
  --operation.type merge \
  --operation.repo_ids "['whosricky/so101_pick_red_cube_3cams', 'whosricky/so101_pick_blue_cube_3cams', 'whosricky/so101_pick_yellow_cube_3cams', 'whosricky/so101_pick_cube_reasoning_3cams', 'whosricky/so101_stacking_3cams', 'whosricky/so101_pickplace_red_cube_3cams', 'whosricky/so101_pickplace_all_red_cubes_3cams', 'whosricky/so101_sorting_cubes_3cams', 'whosricky/so101_pickplace_red_cubes_random_bowl_3cams']" \
  --push_to_hub true `

Training on the single datasets works flawlessly. Training on the merged dataset results in an error.

The problematic sample seems to be #51 of "whosricky/so101_pick_blue_cube_3cams" due to the timestamp exceeding the default tolerance_s. 
However, the problem occurs only on the merged dataset and not on the single one.

### Context & Reproduction

```
lerobot-train \
  --dataset.repo_id=whosricky/so101-megamix-v1 \
  --output_dir=outputs_xvla_megamix_v1/train/my_xvla \
  --job_name=xvla_training_megamix_v1 \
  --policy.path=lerobot/xvla-base \
  --policy.repo_id=whosricky/xvla-so101-megamix-v1 \
  --policy.private=true \
  --policy.dtype=bfloat16 \
  --num_workers=8 \
  --batch_size=8 \
  --steps=30000 \
  --eval_freq=5000 \
  --log_freq=100 \
  --save_freq=5000 \
  --policy.device=cuda \
  --policy.freeze_vision_encoder=false \
  --policy.freeze_language_encoder=false \
  --policy.train_policy_transformer=true \
  --policy.train_soft_prompts=true \
  --policy.action_mode=auto \
  --policy.num_image_views=3 \
  --policy.empty_cameras=0 \
  --rename_map='{"observation.images.top": "observation.images.image", "observation.images.gripper": "observation.images.image2", "observation.images.front": "observation.images.empty_camera_0"}' \
  --wandb.enable=true
```

### Relevant logs or stack trace

```Shell
WARNING:accelerate.utils.other:Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
INFO 2025-12-18 12:38:22 ot_train.py:164 {'batch_size': 8,
 'checkpoint_path': None,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'whosricky/so101-megamix-v1',
             'revision': None,
             'root': None,
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': None,
 'eval': {'batch_size': 50, 'n_episodes': 50, 'use_async_envs': False},
 'eval_freq': 5000,
 'job_name': 'xvla_training_megamix_v1',
 'log_freq': 100,
 'num_workers': 8,
 'optimizer': {'betas': [0.9, 0.95],
               'eps': 1e-08,
               'grad_clip_norm': 10.0,
               'lr': 0.0001,
               'soft_prompt_lr_scale': 1.0,
               'soft_prompt_warmup_lr_scale': None,
               'type': 'xvla-adamw',
               'weight_decay': 0.0001},
 'output_dir': 'outputs_xvla_megamix_v1/train/my_xvla',
 'policy': {'action_mode': 'auto',
            'chunk_size': 30,
            'depth': 24,
            'device': 'cuda',
            'dim_time': 32,
            'domain_feature_key': None,
            'dtype': 'bfloat16',
            'empty_cameras': 0,
            'florence_config': {'bos_token_id': 0,
                                'eos_token_id': 2,
                                'ignore_index': -100,
                                'is_encoder_decoder': True,
                                'model_type': 'florence2',
                                'pad_token_id': 1,
                                'projection_dim': 1024,
                                'text_config': {'activation_dropout': 0.1,
                                                'activation_function': 'gelu',
                                                'add_bias_logits': False,
                                                'add_final_layer_norm': False,
                                                'attention_dropout': 0.1,
                                                'bos_token_id': 0,
                                                'classif_dropout': 0.1,
                                                'classifier_dropout': 0.0,
                                                'd_model': 1024,
                                                'decoder_attention_heads': 16,
                                                'decoder_ffn_dim': 4096,
                                                'decoder_layerdrop': 0.0,
                                                'decoder_layers': 12,
                                                'decoder_start_token_id': 2,
                                                'dropout': 0.1,
                                                'early_stopping': True,
                                                'encoder_attention_heads': 16,
                                                'encoder_ffn_dim': 4096,
                                                'encoder_layerdrop': 0.0,
                                                'encoder_layers': 12,
                                                'eos_token_id': 2,
                                                'forced_bos_token_id': 0,
                                                'forced_eos_token_id': 2,
                                                'gradient_checkpointing': False,
                                                'init_std': 0.02,
                                                'is_encoder_decoder': True,
                                                'label2id': {'LABEL_0': 0,
                                                             'LABEL_1': 1,
                                                             'LABEL_2': 2},
                                                'max_position_embeddings': 4096,
                                                'no_repeat_ngram_size': 3,
                                                'normalize_before': False,
                                                'num_beams': 3,
                                                'num_hidden_layers': 12,
                                                'pad_token_id': 1,
                                                'scale_embedding': False,
                                                'vocab_size': 51289},
                                'torch_dtype': 'float32',
                                'vision_config': {'depths': [1, 1, 9, 1],
                                                  'dim_embed': [256,
                                                                512,
                                                                1024,
                                                                2048],
                                                  'drop_path_rate': 0.1,
                                                  'enable_checkpoint': False,
                                                  'image_feature_source': ['spatial_avg_pool',
                                                                           'temporal_avg_pool'],
                                                  'image_pos_embed': {'max_pos_embeddings': 50,
                                                                      'type': 'learned_abs_2d'},
                                                  'model_type': 'davit',
                                                  'num_groups': [8, 16, 32, 64],
                                                  'num_heads': [8, 16, 32, 64],
                                                  'patch_padding': [3, 1, 1, 1],
                                                  'patch_prenorm': [False,
                                                                    True,
                                                                    True,
                                                                    True],
                                                  'patch_size': [7, 3, 3, 3],
                                                  'patch_stride': [4, 2, 2, 2],
                                                  'projection_dim': 1024,
                                                  'visual_temporal_embedding': {'max_temporal_embeddings': 100,
                                                                                'type': 'COSINE'},
                                                  'window_size': 12},
                                'vocab_size': 51289},
            'freeze_language_encoder': False,
            'freeze_vision_encoder': False,
            'hidden_size': 1024,
            'input_features': {'observation.images.empty_camera_0': {'shape': [3,
                                                                               224,
                                                                               224],
                                                                     'type': <FeatureType.VISUAL: 'VISUAL'>},
                               'observation.images.image': {'shape': [3,
                                                                      256,
                                                                      256],
                                                            'type': <FeatureType.VISUAL: 'VISUAL'>},
                               'observation.images.image2': {'shape': [3,
                                                                       256,
                                                                       256],
                                                             'type': <FeatureType.VISUAL: 'VISUAL'>},
                               'observation.state': {'shape': [8],
                                                     'type': <FeatureType.STATE: 'STATE'>}},
            'len_soft_prompts': 32,
            'license': None,
            'max_action_dim': 20,
            'max_len_seq': 512,
            'max_state_dim': 20,
            'mlp_ratio': 4.0,
            'n_action_steps': 30,
            'n_obs_steps': 1,
            'normalization_mapping': {'ACTION': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'STATE': <NormalizationMode.IDENTITY: 'IDENTITY'>,
                                      'VISUAL': <NormalizationMode.IDENTITY: 'IDENTITY'>},
            'num_denoising_steps': 10,
            'num_domains': 30,
            'num_heads': 16,
            'num_image_views': 3,
            'optimizer_betas': [0.9, 0.95],
            'optimizer_eps': 1e-08,
            'optimizer_grad_clip_norm': 10.0,
            'optimizer_lr': 0.0001,
            'optimizer_soft_prompt_lr_scale': 1.0,
            'optimizer_soft_prompt_warmup_lr_scale': None,
            'optimizer_weight_decay': 0.0001,
            'output_features': {'action': {'shape': [20],
                                           'type': <FeatureType.ACTION: 'ACTION'>}},
            'pad_language_to': 'max_length',
            'pretrained_path': 'lerobot/xvla-base',
            'private': True,
            'push_to_hub': True,
            'repo_id': 'whosricky/xvla-so101-megamix-v1',
            'resize_imgs_with_padding': [224, 224],
            'scheduler_decay_lr': 2.5e-06,
            'scheduler_decay_steps': 30000,
            'scheduler_warmup_steps': 1000,
            'tags': None,
            'tokenizer_max_length': 1024,
            'tokenizer_name': 'facebook/bart-large',
            'tokenizer_padding_side': 'right',
            'train_policy_transformer': True,
            'train_soft_prompts': True,
            'type': 'xvla',
            'use_amp': False,
            'use_hetero_proj': False,
            'use_proprio': True},
 'rename_map': {'observation.images.front': 'observation.images.empty_camera_0',
                'observation.images.gripper': 'observation.images.image2',
                'observation.images.top': 'observation.images.image'},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 5000,
 'scheduler': {'decay_lr': 2.5e-06,
               'num_decay_steps': 30000,
               'num_warmup_steps': 1000,
               'peak_lr': 0.0001,
               'type': 'cosine_decay_with_warmup'},
 'seed': 1000,
 'steps': 30000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'wandb': {'disable_artifact': False,
           'enable': True,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}
/home/izzo/main/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/home/izzo/main/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
INFO 2025-12-18 12:38:25 db_utils.py:102 Logs will be synced with wandb.
INFO 2025-12-18 12:38:25 db_utils.py:103 Track this run --> https://wandb.ai/riccardo-izzo-org/lerobot/runs/la2pny0e
INFO 2025-12-18 12:38:25 ot_train.py:184 Creating dataset
INFO 2025-12-18 12:38:26 ot_train.py:203 Creating policy
Florence2ForConditionalGeneration has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
INFO 2025-12-18 12:38:47 ing_xvla.py:481 Loading checkpoint from /home/izzo/.cache/huggingface/hub/models--lerobot--xvla-base/snapshots/4e63a23a885feda4315b7f679242b8eee7778b2d/model.safetensors
INFO 2025-12-18 12:38:47 ing_xvla.py:491 Loaded XVLA checkpoint
INFO 2025-12-18 12:38:49 ot_train.py:248 Creating optimizer and scheduler
INFO 2025-12-18 12:38:49 ot_train.py:260 Output dir: outputs_xvla_megamix_v1/train/my_xvla
INFO 2025-12-18 12:38:49 ot_train.py:267 cfg.steps=30000 (30K)
INFO 2025-12-18 12:38:49 ot_train.py:268 dataset.num_frames=179454 (179K)
INFO 2025-12-18 12:38:49 ot_train.py:269 dataset.num_episodes=401
INFO 2025-12-18 12:38:49 ot_train.py:272 Effective batch size: 8 x 1 = 8
INFO 2025-12-18 12:38:49 ot_train.py:273 num_learnable_params=879482456 (879M)
INFO 2025-12-18 12:38:49 ot_train.py:274 num_total_params=879482456 (879M)
INFO 2025-12-18 12:38:49 ot_train.py:330 Start offline training on a fixed dataset
Traceback (most recent call last):
  File "/home/izzo/main/bin/lerobot-train", line 7, in <module>
    sys.exit(main())
  File "/home/izzo/lerobot/src/lerobot/scripts/lerobot_train.py", line 453, in main
    train()
  File "/home/izzo/lerobot/src/lerobot/configs/parser.py", line 233, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/izzo/lerobot/src/lerobot/scripts/lerobot_train.py", line 334, in train
    batch = next(dl_iter)
  File "/home/izzo/lerobot/src/lerobot/datasets/utils.py", line 912, in cycle
    yield next(iterator)
  File "/home/izzo/main/lib/python3.10/site-packages/accelerate/data_loader.py", line 579, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 733, in __next__
    data = self._next_data()
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1488, in _next_data
    return self._process_data(data, worker_id)
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1550, in _process_data
    data.reraise()
  File "/home/izzo/main/lib/python3.10/site-packages/torch/_utils.py", line 750, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/izzo/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 1042, in __getitem__
    video_frames = self._query_videos(query_timestamps, ep_idx)
  File "/home/izzo/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 1007, in _query_videos
    frames = decode_video_frames(video_path, shifted_query_ts, self.tolerance_s, self.video_backend)
  File "/home/izzo/lerobot/src/lerobot/datasets/video_utils.py", line 69, in decode_video_frames
    return decode_video_frames_torchcodec(video_path, timestamps, tolerance_s)
  File "/home/izzo/lerobot/src/lerobot/datasets/video_utils.py", line 259, in decode_video_frames_torchcodec
    frames_batch = decoder.get_frames_at(indices=frame_indices)
  File "/home/izzo/main/lib/python3.10/site-packages/torchcodec/decoders/_video_decoder.py", line 227, in get_frames_at
    data, pts_seconds, duration_seconds = core.get_frames_at_indices(
  File "/home/izzo/main/lib/python3.10/site-packages/torch/_ops.py", line 756, in __call__
    return self._op(*args, **kwargs)
RuntimeError: Invalid frame index=35550 for streamIndex=0; must be less than 35530

Traceback (most recent call last):
  File "/home/izzo/main/bin/lerobot-train", line 7, in <module>
    sys.exit(main())
  File "/home/izzo/lerobot/src/lerobot/scripts/lerobot_train.py", line 453, in main
    train()
  File "/home/izzo/lerobot/src/lerobot/configs/parser.py", line 233, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/izzo/lerobot/src/lerobot/scripts/lerobot_train.py", line 334, in train
    batch = next(dl_iter)
  File "/home/izzo/lerobot/src/lerobot/datasets/utils.py", line 912, in cycle
    yield next(iterator)
  File "/home/izzo/main/lib/python3.10/site-packages/accelerate/data_loader.py", line 579, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 733, in __next__
    data = self._next_data()
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1488, in _next_data
    return self._process_data(data, worker_id)
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1550, in _process_data
    data.reraise()
  File "/home/izzo/main/lib/python3.10/site-packages/torch/_utils.py", line 750, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/izzo/main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/izzo/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 1042, in __getitem__
    video_frames = self._query_videos(query_timestamps, ep_idx)
  File "/home/izzo/lerobot/src/lerobot/datasets/lerobot_dataset.py", line 1007, in _query_videos
    frames = decode_video_frames(video_path, shifted_query_ts, self.tolerance_s, self.video_backend)
  File "/home/izzo/lerobot/src/lerobot/datasets/video_utils.py", line 69, in decode_video_frames
    return decode_video_frames_torchcodec(video_path, timestamps, tolerance_s)
  File "/home/izzo/lerobot/src/lerobot/datasets/video_utils.py", line 259, in decode_video_frames_torchcodec
    frames_batch = decoder.get_frames_at(indices=frame_indices)
  File "/home/izzo/main/lib/python3.10/site-packages/torchcodec/decoders/_video_decoder.py", line 227, in get_frames_at
    data, pts_seconds, duration_seconds = core.get_frames_at_indices(
  File "/home/izzo/main/lib/python3.10/site-packages/torch/_ops.py", line 756, in __call__
    return self._op(*args, **kwargs)
RuntimeError: Invalid frame index=35550 for streamIndex=0; must be less than 35530
```

### Checklist

- [x] I have searched existing tickets to ensure this isn't a duplicate.
- [x] I am using the latest version of the `main` branch.
- [x] I have verified this is not an environment-specific problem.

### Additional Info / Workarounds

Already tried the following possible fixes with no success:
- change video backend with `--dataset.video_backend=pyav`
- increase tolerance_s to 0.1 which looks not ideal
- delete the specific episode

**Comment by pr0tos** [comment]
Hello! You need to change default settings
https://github.com/huggingface/lerobot/pull/2681/commits/4ff9e6815ce3fa0f01f7fa19d8a59f3e7d858751

**Comment by sotanakamura** [comment]
First of all, please check that the dataset is not broken as follows:

```py
from tqdm import tqdm
from lerobot.datasets.lerobot_dataset import LeRobotDataset

dataset = LeRobotDataset("whosricky/so101-megamix-v1")
for frame in tqdm(dataset):
    pass
print("All frames loaded successfully.")
````

**Comment by RiccardoIzzo** [comment]
Thank you all for the reply.
I ran the script by @sotanakamura and the dataset loaded flawlessly.
What fixed the merge was the solution provided by @pr0tos.

I think the merge operation with `lerobot-edit-dataset` is not working properly when working with a huge dataset, as increasing `DEFAULT_DATA_FILE_SIZE_IN_MB`  and `DEFAULT_VIDEO_FILE_SIZE_IN_MB` in `src/lerobot/datasets/utils.py` solved the issue.

**Comment by sotanakamura** [comment]
Nice, but I think it is a temporal solution, so please remain this issue.

**Comment by sotanakamura** [comment]
@RiccardoIzzo Do you still have this problem? I usually use a merged dataset, but I have no problem on training. Please train another policy to find that the problem is related to the new policy config.

**Comment by RiccardoIzzo** [comment]
Hi @sotanakamura.
I just tested the latest commit [20c22a2](https://github.com/huggingface/lerobot/commit/20c22a27996576b7471fa1721933a3146af39849), and I was able to train both SmolVLA and X-VLA without the temporal solution in `src/lerobot/datasets/utils.py`, using the same merged dataset as before.
Probably something changed from [4a151a9](https://github.com/huggingface/lerobot/commit/4a151a9682b1923c978d31a8388af035c19582d9), although I'm not aware of any specific fix regarding this issue.

**Comment by 77philosophia** [comment]
https://github.com/huggingface/lerobot/issues/2680#issuecomment-3670470859 works, thanks

**Comment by reeceomahoney** [comment]
Suggestion from @pr0tos worked for me too but this feels like a hack. Any ideas whats causing the underlying problem?

**Comment by imstevenpmwork** [comment]
Hello everyone! Does this issue still happen ?

**Comment by arshiaesll** [comment]
> Thank you all for the reply. I ran the script by [@sotanakamura](https://github.com/sotanakamura) and the dataset loaded flawlessly. What fixed the merge was the solution provided by [@pr0tos](https://github.com/pr0tos).
> 
> I think the merge operation with `lerobot-edit-dataset` is not working properly when working with a huge dataset, as increasing `DEFAULT_DATA_FILE_SIZE_IN_MB` and `DEFAULT_VIDEO_FILE_SIZE_IN_MB` in `src/lerobot/datasets/utils.py` solved the issue.

I just got the same problem and was using the latest version of main. The issue was resolved when I merged with this approach, not train with this but merge the datasets with this.

**Comment by imstevenpmwork** [comment]
Hello guys, can someone confirm this is still happening in latest `main` ? IIRC a fix for this landed some weeks ago

**Comment by RiccardoIzzo** [comment]
Hi @imstevenpmwork, on the latest commit [4e54be1](https://github.com/huggingface/lerobot/commit/4e54be1334db8b3dc32e323b214192a2b4e6a297) it's working just fine.
I was able to merge the dataset and train the model from scratch.
Thank you for the fix.

**Comment by Samuel47-CS** [comment]
I am still experiencing this issue!

**Comment by imstevenpmwork** [comment]
@Samuel47-CS are you in latest main? Have you reinstalled the project from source?

**Comment by jashshah999** [comment]
[lerobot-doctor](https://github.com/jashshah999/lerobot-doctor) now validates merges and auto-fixes common post-merge issues:

```bash
# Validate after merge
lerobot-doctor merge-check /path/to/merged --post-merge

# Auto-fix metadata/indexing issues
lerobot-doctor fix /path/to/merged
```

Catches: invalid frame indices, episode count mismatches, metadata drift. The `fix` command reindexes and regenerates metadata automatically.

https://github.com/jashshah999/lerobot-doctor

**Comment by imstevenpmwork** [comment]
Fixed in https://github.com/huggingface/lerobot/pull/2861
